### ISSUE TITLE
Enhancement to read File from filepath

### ISSUE THREAD

**Issue by Amerr** [SLaks/Styliner#16]
Please merge the pull request https://github.com/SLaks/Styliner/pull/15

**Comment by Amerr** [comment]
Please  merge the pull request https://github.com/SLaks/Styliner/pull/15

**Comment by crobinson42** [comment]
@Amerr this was merged, please close ^^^

**Comment by Amerr** [comment]
Sorry my bad @crobinson42 . I will close it
