### ISSUE TITLE
Move to q-io v2 branch to avoid ES6 issues

### ISSUE THREAD

**Issue by scandox** [SLaks/Styliner#17]
At the moment some of the shim functions from collections 0.20 cause problems with ES6. For example the `find` shim actually has the functionality of `findIndex`. After including Styliner in a server side project using harmony, my `find` was monkeypatched by collections.

@kriskowal suggested moving the v2 branch of q-io. I updated my Styliner installation to use >=2.0.6 and cannot see any problems, after cursory testing. This version of q-io uses collections>=2.0.2.

Do you think it would be a big change to make?

**Comment by SLaks** [comment]
That should be fine; feel free to send a PR.
